version: 2

mkdocs:
 configuration: mkdocs.yml

build:
   image: latest

python:
   version: 3.6
   system_packages: true
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .

formats: []