site_name: Deep Point Cloud Benchmark
site_url: https://nicolas-chaulet.github.io/deeppointcloud-benchmarks/
repo_url: https://github.com/nicolas-chaulet/deeppointcloud-benchmarks

nav:
    - Home: index.md
    - Installation: src/installation.md
    - Convolution Type Introduction: src/conv_type.md
    - Introduction by Example: how_to_do/how_to_do.md
    - Core: src/core.md
    - Models: src/models.md
    - Datasets: src/datasets.md
    - Modules: src/modules.md
    - Logging: src/logging.md
    - ModelCheckpoint: src/modelcheckpoint.md
    - Visualization: src/visualization.md
    - API:
        - core: src/api/core.md



theme: readthedocs

markdown_extensions:
    - mkautodoc
    - toc:
        permalink: "#"
        baselevel: 2

extra_css:
    - css/custom.css

extra:
    version: 0.1.0