site_name: Deep Point Cloud Benchmark
site_url: https://nicolas-chaulet.github.io/deeppointcloud-benchmarks/
repo_url: https://github.com/nicolas-chaulet/deeppointcloud-benchmarks

nav:
    - Home: index.md
    - Getting started:
        - Installation: src/gettingstarted/installation.md
        - Train!: src/gettingstarted/trainmodel.md
        - Project's organisation: src/gettingstarted/projectorganisation.md
    - Core features:
        - Configuration: src/corefeatures/configuration.md
        - Data structures: src/corefeatures/datastructures.md
        - Visualization: src/corefeatures/visualization.md
        - ModelCheckpoint: src/corefeatures/modelcheckpoint.md
        - Datasets: src/corefeatures/datasets.md
        - Logging: src/corefeatures/logging.md
    - Introduction by Example:
        - Create a new dataset: src/howtos/createdataset.md
        - Create a new model: src/howtos/createmodel.md
        - Run new experiment: src/howtos/runexperiment.md
    - Core: src/core.md
    - Models: src/models.md

    - Modules: src/modules.md
   
    - API:
        - core: src/api/core.md



theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - bash
    navigation_depth: 4
    titles_only: False

markdown_extensions:
    - mkautodoc
    - toc:
        permalink: "#"

extra_css:
    - css/custom.css

extra:
    version: 0.1.0