# Those arguments defines the training hyper-parameters
training:
    shuffle: True
    num_workers: 6
    batch_size: 16
    cuda: 1
    precompute_multi_scale: True # Compute multiscate features on cpu for faster training / inference
    epochs: 100
    grad_clip: 100
    optimizer:
        class: SGD
        params:
            momentum: 0.98
            weight_decay: 1e-3
            lr: 0.01
    learning_rate:
        scheduler_type: "step_decay"
        base_lr: ${optimizer.params.lr}
        lr_decay: 0.5
        decay_step: 200000
        lr_clip: 1e-5
    weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
    enable_cudnn: True
    checkpoint_dir: ""
    resume: True
