# Those arguments defines the training hyper-parameters
training:
    shuffle: True
    num_workers: 4
    batch_size: 16
    cuda: 1
    precompute_multi_scale: True # Compute multiscate features on cpu for faster training / inference
    epochs: 100
    grad_clip: -1
    base_lr: 0.001
    optim:
        optimizer:
            class: Adam
            params:
                lr: ${base_lr} # The path is cut from training
        scheduler: ${scheduler}
    weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
    enable_cudnn: True
    checkpoint_dir: ""
    resume: True

# Those arguments within experiment defines which model, dataset and task to be created for benchmarking
# parameters for Weights and Biases
wandb:
    project: shapenet-pn2
    log: True
    notes: "Multihead"
    name: "kpconv-multihead"

# parameters for TensorBoard Visualization
tensorboard:
    log: True
