num_workers: 2
batch_size: 16
cuda: 0
weight_name: "val" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "/workspace/outputs/benchmark/benchmark-KPConvPaper-20220630_114943" # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: KPConvPaper
enable_dropout: False
output_path: "/workspace/outputs/" # Where the output goes
input_path: "/workspace/data" # Folder where to find the data

# Dataset specific
defaults:
    - dataset: ""
      optional: True